```{r}
# Load libraries
library(tidyverse)
library(tidymodels)
library(caret)
library(gridExtra)
library(vip)
library(ranger)

# Read the dataset
drug <- read.csv("drug_data-2.csv")

names(drug) = c("ID", "Age", "Gender", "Education", "Country", "Ethnicity",
"Nscore", "Escore", "Oscore", "Ascore", "Cscore", "Impulsive",
"SS", "Alcohol", "Amphet", "Amyl", "Benzos", "Caff", "Cannabis",
"Choc", "Coke", "Crack", "Ecstasy", "Heroin", "Ketamine", "Legalh",
"LSD", "Meth", "Mushrooms", "Nicotine", "Semer", "VSA")

drug[drug == "CL0"] = "No"
drug[drug == "CL1"] = "No"
drug[drug == "CL2"] = "Yes"
drug[drug == "CL3"] = "Yes"
drug[drug == "CL4"] = "Yes"
drug[drug == "CL5"] = "Yes"
drug[drug == "CL6"] = "Yes"

drug_clean = drug %>% mutate_at(vars(Age:Ethnicity), funs(as_factor)) %>%
mutate(Age = factor(Age, labels = c("18_24", "25_34", "35_44", "45_54",
"55_64", "65_"))) %>%
mutate(Gender = factor(Gender, labels = c("Male", "Female"))) %>%
mutate(Education = factor(Education, labels = c("Under16", "At16", "At17", "At18",
"SomeCollege","ProfessionalCert",
"Bachelors", "Masters",
"Doctorate"))) %>%
mutate(Country = factor(Country, labels = c("USA", "NewZealand", "Other", "Australia",
"Ireland","Canada","UK"))) %>%
mutate(Ethnicity = factor(Ethnicity, labels = c("Black", "Asian", "White",
"White/Black", "Other",
"White/Asian", "Black/Asian"))) %>%
mutate_at(vars(Alcohol:VSA), funs(as_factor)) %>%
select(-ID)

drug_clean = drug_clean %>% select(!(Alcohol:Mushrooms)) %>% select(!(Semer:VSA))
```

```{r}
any(is.na(drug_clean))
```

```{r}
set.seed(1234)

split <- initial_split(drug_clean, prop = 0.7, strata = Nicotine)
train <- training(split)
test <- testing(split)

nrow(train)
```

```{r}
ggplot(train, aes(x = Age, fill = Nicotine)) + geom_bar() + theme_minimal()
```

```{r}
ggplot(train, aes(x = Impulsive, fill = Nicotine)) + geom_boxplot() + theme_minimal()
```

```{r}
# Train Random Forest Model

set.seed(123)

# Define recipe
rf_recipe <- recipe(Nicotine ~ ., data = train)

# Define model
rf_model <- rand_forest(
  mode = "classification",
  mtry = tune(),
  min_n = tune(),
  trees = 100
) %>% 
  set_engine("ranger", importance = "impurity")

# Define cross-validation
cv_folds <- vfold_cv(train, v = 5)

# Define tuning grid
grid <- grid_regular(mtry(range = c(2, 8)), min_n(range = c(5, 20)), levels = 10)

# Workflow
rf_workflow <- workflow() %>%
  add_model(rf_model) %>%
  add_recipe(rf_recipe)

# Tune model
tuned_results <- tune_grid(rf_workflow, resamples = cv_folds, grid = grid, metrics = metric_set(accuracy))

# Visualize results
autoplot(tuned_results)
```

```{r}
# Select the best parameters
best_params <- select_best(tuned_results, metric = "accuracy")

# Finalize the workflow
final_workflow <- rf_workflow %>%
  finalize_workflow(best_params)

# Fit the model to the training data
final_model <- final_workflow %>%
  fit(train)

# Check variable importance
vip(final_model)

```

```{r}
# Training accuracy
train_preds <- predict(final_model, train) %>% bind_cols(train)
train_acc <- mean(train_preds$.pred_class == as.factor(train_preds$Nicotine))
round(train_acc, 4)

# Naive accuracy
naive_acc <- max(prop.table(table(train$Nicotine)))
round(naive_acc, 4)

# Test accuracy
test_preds <- predict(final_model, test) %>% bind_cols(test)
test_acc <- mean(test_preds$.pred_class == test_preds$Nicotine)
round(test_acc, 4)

```

```{r}
abs(train_acc - test_acc)
```

